// Types
import type { Metadata, Viewport } from 'next';
import type { PropsWithChildren } from 'react';

// Styles
import { body, display, mono } from '@/styles/fonts';
import '@/styles/globals.css';

// Lib
import { ThemeProvider } from '@/lib/providers/theme-provider';

// Utils
import { cn } from '@/utils/cn';

export const viewport: Viewport = {
    colorScheme: 'light',
};

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
    const fonts = [body.variable, display.variable, mono.variable];

    return (
        <html lang="en" className={cn(fonts, 'scroll-smooth dark-mode')}>
            <body className="bg-primary text-tertiary antialiased">
                <ThemeProvider>{children}</ThemeProvider>
            </body>
        </html>
    );
}
